---
- name: Remove content and directory
  file:
    path: /home/vagrant/prod/03.npm_Deploy/
    state: absent

- name: create directory
  file:
    path: /home/vagrant/prod/03.npm_Deploy
    state: directory
    recurse: yes

- name: clone repo
  git:
    repo: https://github.com/sergeikoltochihin/TODOApp.git
    dest: /home/vagrant/prod/03.npm_Deploy
    version: master

- name: Install packages from json
  npm:
    path: /home/vagrant/prod/03.npm_Deploy
