---
- name: Check connection localhost
  wait_for:
    host: "localhost"
    port: "4201"
    state: started
    timeout: 3
  register: out

- name: Check content
  uri:
    url: http://prod.com
    return_content: yes
  register: this
  failed_when: "'Todo' not in this.content"
